discovery-server:
  image: artlovan/discovery-server
  ports:
    - 8761:8761
  environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP

config-service:
  image: artlovan/datetime-app
  environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
  ports:
    - 8001:8001
  links:
    - discovery-server
  environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP


